source.. = WEB-INF/src/
output.. = target/classes/
bin.includes = META-INF/,\
               .,\
               WEB-INF/web.xml,\
               WEB-INF/xsd/,\
               plugin.xml,\
               OSGI-INF/,\
               lib/idempiere-xmlbeans.jar,\
               lib/cors-filter-2.6.jar,\
               lib/java-property-utils-1.9.1.jar
src.includes = lib/,\
               WEB-INF/web.xml,\
               WEB-INF/xsd/
